import '@babel/polyfill';
import React from 'react';
import { hydrate, render } from 'react-dom';
import App from './app';
const modernBrowser = 'fetch' in window;

// check if polyfills are needed
if (!modernBrowser) {
	// create and append polyfill script that is generated by webpack
	import(/* webpackChunkName: "polyfill" */ 'whatwg-fetch');
}

// Check that service workers are supported (e.g. only https)
if ('serviceWorker' in navigator) {
	//navigator.serviceWorker.register('/sw.js');
}

// server side rendering only in production mode
if (process.env.NODE_ENV === 'production') {
	hydrate(<App />, document.getElementById('app'));
} else {
	render(<App />, document.getElementById('app'));
}
