import '@babel/polyfill';

export const GLOBALS = {
	html: document.querySelector('html'),
	body: document.querySelector('body'),
	window,
	doc: document,
	currentBreakpoint: '"xs"',
	currentOrientation: '"portrait"',
	breakpoints: {
		xs: 320,
		sm: 480,
		md: 768,
		lg: 992,
		xl: 1200
	}
};

/**
 * check for browser capabilities and load polyfills if needed
 * @param callback - run callback after successful import
 */
function loadPolyfills(callback) {
	const modernBrowser = 'fetch' in window;

	// check if polyfills are needed
	if (!modernBrowser) {
		// create and append polyfill script that is generated by webpack
		import(/* webpackChunkName: "polyfill" */ 'whatwg-fetch').then(() => {
			callback();
		});
	} else {
		callback();
	}
}

/**
 * load all needed dependencies for the components
 * @param callback - run callback after successful import
 */
function loadDependencies(callback) {}

function loadServiceWorker() {
	// Check that service workers are supported (e.g. only https)
	if ('serviceWorker' in navigator) {
		navigator.serviceWorker.register('/sw.js');
	}
}

/**
 * initialize components
 */
function loadComponents() {
	if (document.querySelector('.nav-main')) {
		import(/* webpackChunkName: "nav-main" */ '../components/nav-main/nav-main').then(
			component => {
				component.init();
			}
		);
	}

	if (document.querySelector('[data-parallax-speed]')) {
		import(/* webpackChunkName: "handler" */ './handle/parallax-handler').then(component => {
			component.default();
		});
	}

	if (document.querySelector('.slider')) {
		import(/* webpackChunkName: "slider" */ '../components/slider/slider').then(component => {
			component.init();
		});
	}

	if (document.querySelector('img.lazyload')) {
		import(/* webpackChunkName: "lazyload" */ 'lazysizes');
	}

	if (document.querySelector('.preact-list')) {
		import(/* webpackChunkName: "preact-list" */ '../components/preact-list/preact-list');
	}
}

(function() {
	loadPolyfills(() => {
		loadComponents();
		loadServiceWorker();
	});
})();
