import '@babel/polyfill';

/*
 * Capitan - global.js
 * initialization of components, polyfills, utils, handlers and functions
 */

/**
 * check for browser capabilities and load polyfills if needed
 * @param callback - run callback after successful import
 */
function loadPolyfills(callback) {
	const modernBrowser = (
		'fetch' in window
	);

	// check if polyfills are needed
	if (!modernBrowser) {
		// create and append polyfill script that is generated by webpack
		import(/* webpackChunkName: "polyfill" */ 'whatwg-fetch').then(() => {
			callback();
		});
	} else {
		callback();
	}
}

/**
 * load all needed dependencies for the components
 * @param callback - run callback after successful import
 */
function loadDependencies(callback) {
}

/**
 * initialize components
 */
function loadComponents() {
	if (document.querySelector('.nav-main')) {
		import(/* webpackChunkName: "nav-main" */ '../components/nav-main/nav-main').then((component) => {
			component.init();
		});
	}

	if (document.querySelector('.stage')) {
		import(/* webpackChunkName: "stage" */ '../components/stage/stage').then((component) => {
			component.init();
		});
	}

	if (document.querySelector('.slider')) {
		import(/* webpackChunkName: "stage" */ '../components/slider/slider').then((component) => {
			component.init();
		});
	}
}

(function () {
	loadPolyfills(() => {
		loadComponents();
	});
})();
