import '@babel/polyfill';
import { hot } from 'react-hot-loader/root';
import React from 'react';
import LayoutStyle from './styles/layout';
import TypoStyle from './styles/typo';
import Home from './pages/Home';

/**
 * check for browser capabilities and load polyfills if needed
 * @param callback - run callback after successful import
 */
function loadPolyfills() {
	const modernBrowser = 'fetch' in window;

	// check if polyfills are needed
	if (!modernBrowser) {
		// create and append polyfill script that is generated by webpack
		import(/* webpackChunkName: "polyfill" */ 'whatwg-fetch');
	}
}

function loadServiceWorker() {
	// Check that service workers are supported (e.g. only https)
	if ('serviceWorker' in navigator) {
		navigator.serviceWorker.register('/sw.js');
	}
}

// loadPolyfills();
loadServiceWorker();

const App = hot(() => (
	<div>
		<LayoutStyle />
		<TypoStyle />
		<Home />
	</div>
));

export default App;
